version: '3' 

services:
  datanode:
    extends:
      file: hadoop.yml
      service: datanode
  namenode:
    extends:
      file: hadoop.yml
      service: namenode
  hive-server:
    image: fjardim/hive
    container_name: hive-server
    hostname: hive_server
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    depends_on:
      - hive-metastore
    volumes:
      - ./data/teste:/teste
    mem_limit: 1g
    networks:
      - hadoop
  
  
  hive-metastore:
    image: fjardim/hive
    container_name: hive_metastore
    hostname: hive_metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
    depends_on:
      - hive-metastore-postgresql
    mem_limit: 1g
    networks:
      - hadoop
  
  
  hive-metastore-postgresql:
    image: fjardim/hive-metastore
    container_name: hive-metastore-postgresql
    hostname: hive_metastore_postgresql
    volumes:
      - ./data/hive_pgdata:/var/lib/postgresql/data
    depends_on:
      - datanode
    mem_limit: 1g
    networks:
      - hadoop
networks:
  hadoop:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1
