version: '3'

services:
  spark-master:
    container_name: master
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - '8082:8080'
      - '7077:7077'
    volumes:
      - spark_master_data:/bitnami
    networks:
      - hadoop

  spark-worker:
    container_name: worker
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
    ports:
      - '8081:8081'
    volumes:
      - spark_worker_data:/bitnami
    networks:
      - hadoop

networks:
  hadoop:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1


volumes:
  spark_master_data:
    driver: local
  spark_worker_data:
    driver: local
